import streamlit as st
import json
from snowflake.snowpark.context import get_active_session

# ── Config ──────────────────────────────────────────────────
AGENT_FQN = "SUPPLY_CHAIN.CORE.SUPPLY_CHAIN_AGENT"

MAX_MESSAGES_PER_SESSION = 50
MAX_HISTORY_TURNS = 10
MAX_INPUT_CHARS = 500

PERSONAS = {
    "Planning": {
        "icon": "📋",
        "prefix": "You are advising a demand planning manager. Focus on inventory levels, days of inventory, reorder points, and demand forecasting. Highlight stock-out risks and overstock situations.",
        "starters": [
            "What are the current days of inventory by part category?",
            "Which plants have inventory below the reorder point?",
            "Show monthly order volume trend",
        ],
    },
    "Procurement": {
        "icon": "🤝",
        "prefix": "You are advising a procurement lead. Focus on supplier performance, OTD, fill rate, lead times, and spend analysis. Flag underperforming suppliers.",
        "starters": [
            "What is OTD by supplier?",
            "Which suppliers have the worst delivery delays?",
            "Who are the top 20 customers by spend?",
        ],
    },
    "Logistics": {
        "icon": "🚚",
        "prefix": "You are advising a logistics manager. Focus on shipment tracking, landed cost, carrier performance, partial shipments, and delivery SLAs. Optimize shipping costs.",
        "starters": [
            "What is the landed cost by carrier?",
            "What is the shipment status distribution?",
            "Show fill rate by plant",
        ],
    },
}

session = get_active_session()


def call_agent(messages):
    payload = json.dumps({"messages": messages})
    escaped = payload.replace("'", "''")
    sql = f"SELECT TRY_PARSE_JSON(SNOWFLAKE.CORTEX.DATA_AGENT_RUN('{AGENT_FQN}', '{escaped}')) AS resp"
    result = session.sql(sql).collect()
    raw = result[0]["RESP"]
    if isinstance(raw, str):
        return json.loads(raw)
    return raw


def extract_text_and_sql(response):
    text_parts = []
    sql_parts = []
    if isinstance(response, str):
        return response, []
    if "error" in response or "message" in response:
        return response.get("message", response.get("error", str(response))), []
    for item in response.get("content", []):
        if item.get("type") == "text":
            text_parts.append(item["text"])
        elif item.get("type") == "tool_result":
            for c in item.get("tool_result", {}).get("content", []):
                if c.get("type") == "json" and "sql" in c.get("json", {}):
                    sql_parts.append(c["json"]["sql"])
    return "\n\n".join(text_parts), sql_parts


# ── UI ──────────────────────────────────────────────────────
st.set_page_config(page_title="Supply Chain Agent", page_icon="📦", layout="wide")
st.title("📦 Supply Chain Analytics Agent")

with st.sidebar:
    st.header("Persona")
    persona = st.radio(
        "I am a...",
        list(PERSONAS.keys()),
        format_func=lambda p: f"{PERSONAS[p]['icon']} {p}",
    )
    st.divider()
    st.caption("Suggested questions:")
    for q in PERSONAS[persona]["starters"]:
        if st.button(q, key=f"starter_{q}", use_container_width=True):
            st.session_state["starter_q"] = q
    st.divider()
    if st.button("Clear chat", use_container_width=True):
        st.session_state["messages"] = []
        st.session_state["display"] = []
        st.rerun()

if "messages" not in st.session_state:
    st.session_state["messages"] = []
if "display" not in st.session_state:
    st.session_state["display"] = []

for msg in st.session_state["display"]:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("sql"):
            with st.expander("SQL generated by agent"):
                for s in msg["sql"]:
                    st.code(s, language="sql")

user_input = st.chat_input("Ask a supply chain question...")
if "starter_q" in st.session_state:
    user_input = st.session_state.pop("starter_q")

if user_input:
    if len(user_input) > MAX_INPUT_CHARS:
        st.warning(f"Message too long ({len(user_input)} chars). Max is {MAX_INPUT_CHARS}.")
    elif len(st.session_state["display"]) >= MAX_MESSAGES_PER_SESSION * 2:
        st.warning(f"Session limit reached ({MAX_MESSAGES_PER_SESSION} questions). Clear chat to continue.")
    else:
        st.session_state["display"].append({"role": "user", "content": user_input})
        with st.chat_message("user"):
            st.markdown(user_input)

        persona_prefix = PERSONAS[persona]["prefix"]
        augmented = f"[Persona context: {persona_prefix}]\n\n{user_input}"

        st.session_state["messages"].append(
            {"role": "user", "content": [{"type": "text", "text": augmented}]}
        )

        recent_messages = st.session_state["messages"][-(MAX_HISTORY_TURNS * 2):]

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                try:
                    response = call_agent(recent_messages)
                    text, sqls = extract_text_and_sql(response)
                    if not text:
                        text = "The agent returned no text response. Please try rephrasing."
                    st.markdown(text)
                    if sqls:
                        with st.expander("SQL generated by agent"):
                            for s in sqls:
                                st.code(s, language="sql")
                    st.session_state["display"].append(
                        {"role": "assistant", "content": text, "sql": sqls}
                    )
                    st.session_state["messages"].append(
                        {"role": "assistant", "content": [{"type": "text", "text": text}]}
                    )
                except Exception as e:
                    st.error(f"Error calling agent: {e}")
